# Generated by Django 4.2.4 on 2023-08-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
            ],
        ),
    ]
